apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-mig-mode-pod
  name: nvidia-mig-mode-pod
  namespace: gpu-operator-resources
  annotations:
    openshift.io/scc: nvidia-driver
    # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
    # reserves resources for critical add-on pods so that they can be rescheduled after
    # a failure.  This annotation works in tandem with the toleration below.
    scheduler.alpha.kubernetes.io/critical-pod: ""
spec:
  tolerations:
  - key: nvidia.com/gpu # certainly wrong
    operator: Exists
    effect: NoSchedule
  serviceAccount: nvidia-driver
  serviceAccountName: nvidia-driver
  hostPID: true
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: OnFailure
  containers:
  - image: "FILLED BY THE OPERATOR"
    imagePullPolicy: Always
    name: nvidia-mig-mode-ctr
    command: ["bash", "-x", "/mnt/helper/run.sh"]
    lifecycle:
      postStart:
        exec:
          command:
          - /mnt/helper/start-hook.sh
    securityContext:
      privileged: true
      seLinuxOptions:
        level: "s0"
    volumeMounts:
    - mountPath: /mnt/helper/
      name: run-sh
      readOnly: true
  volumes:
  - name: run-nvidia
    hostPath:
      path: /run/nvidia
  - configMap:
      defaultMode: 0744
      name: nvidia-mig-mode-run-sh
    name: run-sh
  nodeSelector:
    nvidia.com/gpu.present: "true"
