apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-container-toolkit
  namespace: gpu-operator-resources
data:
  startup-hook.sh : |
    #! /bin/bash

    MOD=nvidia

    # lsmod is not available
    while ! grep "$MOD" /proc/modules -q; do
      echo "Module $MOD isn't loaded."
      sleep 5
    done

  ready-probe.sh : |
    #! /bin/bash

    if ! ps aux | grep -v grep | grep /work/nvidia-toolkit ; then
      echo "nvidia-toolkit not running"
      exit 1
    fi
